db:
  image: "postgres:9.4"
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  volumes_from:
    - dbdata
dbdata:
  image: "postgres:9.4"
  volumes:
    - /var/lib/postgres
  command: "true"
web:
  build: "."
  environment:
    MIX_ENV: "prod"
    PORT: 4000
  ports:
    - "80:4000"
  links:
    - "db:db"

