db:
  image: "postgres:9.4"
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: wolves_api_prod
  volumes_from:
    - dbdata
dbdata:
  image: "postgres:9.4"
  volumes:
    - /var/lib/postgres
  command: "true"
web:
  build: "gladis/wolves_api"
  environment:
    MIX_ENV: "prod"
    PORT: 4000
  ports:
    - "4000:4000"
  links:
    - "db:db"

